### ISSUE TITLE
TinkerPop 3

### ISSUE THREAD

**Issue by vanthome** [ArangoDB-Community/tinkerpop-arangodb-provider#15]
Hi, is there any chance that this will be upped to TP3?
I would love to play around with ArangoDB through a TP3 layer.
thanks

**Comment by dminkovsky** [comment]
+1, would be great. TP3 is pretty nice!

**Comment by eugene-kamenev** [comment]
+1 here, TP3 released few days ago.

**Comment by jan-zajic** [comment]
+1

**Comment by kerler** [comment]
+1

**Comment by skimming** [comment]
+1

**Comment by leemit** [comment]
+1 on TP3 for ArangoDB

**Comment by analytically** [comment]
+1

**Comment by ttschampel** [comment]
+1

**Comment by liuguoguo** [comment]
+1

**Comment by nharris85** [comment]
+1

**Comment by okram** [comment]
TinkerPop 3.2.2 will provide Gremlin `Bytecode`. Bytecode is a language agnostic "nested lists" representation of Gremlin. It enables the communication of a traversal between VMs (Python, Ruby, Java, Groovy, Scala, etc.). Currently, its advertised as a way for language's to easily host Gremlin (i.e. language drivers).

http://tinkerpop.apache.org/docs/3.2.2-SNAPSHOT/reference/#gremlin-variants
http://tinkerpop.apache.org/docs/3.2.2-SNAPSHOT/tutorials/gremlin-language-variants/

However, it is possible to translate Bytecode into another language. For instance:

(1) SPARQL -> Gremlin Bytecode

- https://github.com/dkuppitz/sparql-gremlin
- doesn't use bytecode currently. the old translation model was convoluted.

(2) SQL -> Gremlin Bytecode 

- https://github.com/twilmes/sql-gremlin
- doesn't use bytecode currently. the old translation model was convoluted.

Thus, ArangoDB can create Gremlin Bytecode -> AQL. To take advantage of the language bindings provided by Apache TinkerPop, ArangoDB would also implement `RemoteConnection` in their "server" which is a WebSockets protocol. http://tinkerpop.apache.org/docs/3.2.2-SNAPSHOT/dev/provider/#_graph_driver_provider_requirements ... Thus, ArangoDB gets Gremlin bytecode, translate it to AQL, executes it, and return the result set over the WebSockets connection.

With this model, then they automagically support SQL and SPARQL as you can go:

SPARQL -> Gremlin Bytecode -> AQL

What does that translation look like?

```sql
SELECT DISTINCT ?name
WHERE {
  ?a v:label "person" .
  ?a e:created ?b .
  ?b v:name ?name .
    FILTER (?age > 30)
}
```

```lisp
[
  [ "V", []],
  [ "match", [
    [["as", ["a"]], ["hasLabel", ["person"]]],
    [["as", ["a"]], ["out", ["created"]], ["as",["b"]]],
    [["as", ["b"]], ["values", ["name"]], ["as",["name"]]]]
  [ "where", ["age", gt(30)]],
  [ "dedup", ["name"]],
  [ "select", ["name"]]
]
```

AQL .. I dunno.

**Comment by ptpaterson** [comment]
Are there any updates or plans to move forward with this?

[gremlin-javascript](https://github.com/jbmusso/gremlin-javascript) does not support bytecode queries, which poses an obstical, given the nodeJS environment around ArangoDB.

Trying to decompile a gremlin Bytecode into AQL sounds involved enough -- Perhaps it could be a clever work around to use a gremlin driver outside of official ArangoDB support.

It seems, though, that the Bytecode queries are meant to be consumed natively by an actual gremlin server.  Are there plans to develop an implementation of the Gremlin Structure API (blueprints for TP3)?

**Comment by dothebart** [comment]
We currently don't have resources to work on this. Community contributions are welcome.

**Comment by MrPieces** [comment]
There is a community contribution of @arcanefoam to get the Gremlin Integration ArangoDB 3 and Tinkerpop 3 ready... you can find the PR here: https://github.com/arangodb/blueprints-arangodb-graph/pull/29. Maybe we can get this rollin together

**Comment by arcanefoam** [comment]
My pull request has not (apparently) received any notice by the dev team. @MrPieces, I would be happy to fork this into a separate project in the mean time if you, and other community members, wish to try it, use it and provide feed back to get it polished.

**Comment by durgagokina** [comment]
@arcanefoam - I am interested in TinkerPop capability. Could you share what is pending at this point in terms of functionality.

**Comment by arcanefoam** [comment]
@durgagokina  - You can get the code from my fork [(t3 fork)](https://github.com/arcanefoam/blueprints-arangodb-graph). I think all of it is implemented, at least the tinkerpop3 test suit (that applies) has been covered and passed. But until people try it out there we wont find the bugs ;). Please fell free to file any bugs against my fork and I will be happy to look into them.

**Comment by dothebart** [comment]
Hi everyone, 
after a short internal discussion this Repository has been moved to the ArangoDB-Community github organization. 
As you have already seen, @arcanefoam is working actively on this to make this happen. 
He is now the owner of this community driven project. 
Please join him by doing code reviews, patches, testing or discussions to move forward.

**Comment by arcanefoam** [comment]
Hi Everyone,
I will make some code base clean up and update the pom, README, etc., to reflect the new status/name of the project and will merge my changes into master so we can go from there.

**Comment by arcanefoam** [comment]
This has been merged into master now!
