### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by francoisprunier** [ArangoDB-Community/tinkerpop-arangodb-provider#23]
Hi,

Unless I'm not using the API right, I think there is a problem in a cache not being cleared leading to a memory leak:

The member variable vertexCache defined in ArangoDBBatchVertex is never cleared. Thus if you do a very large bulk load, it grows indefinitely. 

I think that vertexCache.clear should be called when its size reaches a configurable threshold, maybe defaulting to some ratio of the batch size for example.

I'm using version 1.0.14

Thanks,
François

**Comment by francoisprunier** [comment]
Do you need more information ? I had to build a facade object to get access to the maps and clear the cache, it's not practical, it would be easy to configure it though. I can try to come up with a pull request if you'd like.

**Comment by arcanefoam** [comment]
Closing this as the code base and versions supported have changed significantly. Please reopen if you continue to experience this issue.
