### ISSUE TITLE
blueprints-arangodb-graph doesn't support arangodb-java-driver 3.0.0

### ISSUE THREAD

**Issue by liuguoguo** [ArangoDB-Community/tinkerpop-arangodb-provider#24]
Hi all,
Now Arangodb has already released 3.0, but my project uses the current blueprints-Arangodb-graph, it caused we can't experience the latest ArangoDB version. Have you guys plan to integrate the latest version of arangodb-java-driver?

**Comment by marcoy** [comment]
We are running the same problem. We want to use TinkerPop3 with the latest ArangoDB. Any updates?

**Comment by softwareishappiness** [comment]
We want to use Gremlin too? Any word on TinkerPop3 with ArangoDB3??

**Comment by arcanefoam** [comment]
This is now suported!
