### ISSUE TITLE
Missing logback.xml file when running and instructions to reduce logging

### ISSUE THREAD

**Issue by kuzeko** [ArangoDB-Community/tinkerpop-arangodb-provider#26]
The only `logback.xml` is in test, this causes the `[DEBUG]` messages to be printed, which includes http requests too.

Either add a conf file for logging INFO/WARN and above, or instructions to configure the logging level in the documentation.
For instance how to set the `$CLASSPATH` pointing to a user defined `logback.xml` file.
Ideally this should be best passed via CLI command too.

**Comment by kuzeko** [comment]
Complete steps to fix this:

1. create config `PATH_TO/confs/` directory with inside:
        a. file `confs/arangod.conf`
        b. file `confs/logback.xml`

2. set env. variable `CLASSPATH`:

       export CLASSPATH=PATH_TO/confs

3.  you can start `arangod` as   follows:

        arangod  --daemon --pid-file /etc/arangodb/arangodb.pid -c PATH_TO/confs/arangod.conf


The content of  `confs/arangod.conf` should contain:

      ```
      [log]
      ## info, warning, or error
      level = info
      file = PATH_TO/logs/arangodb.log
      ```

The content of the  `confs/logback.xml`

```xml
<configuration>
  <!-- Arango log4j conf -->
  <appender name="CONSOLE"
      class="ch.qos.logback.core.ConsoleAppender">
          <!-- deny all events with a level below INFO, that is TRACE and DEBUG -->
           <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
                <level>INFO</level>
           </filter>
           <encoder>
           <pattern>
                 %-4relative [%thread] %-5level %logger{30} - %msg%n
           </pattern>
           </encoder>
  </appender>
  <root level="DEBUG">
     <appender-ref ref="CONSOLE" />
  </root>
</configuration>
```

**Comment by arcanefoam** [comment]
Closing this as the code base and versions supported have changed significantly. Please reopen if you continue to experience this issue.
