### ISSUE TITLE
Queries translated with "for i in GRAPH_VERTICES(@graphName , @vertexExample, @options)" Kill the Server

### ISSUE THREAD

**Issue by kuzeko** [ArangoDB-Community/tinkerpop-arangodb-provider#28]
I'm using gremlin 2.6.0 with arango 2.8.11 on a 24 cores 128GB server.

Any query that results into
`for i in GRAPH_VERTICES(@graphName , @vertexExample, @options) ...`

e.g.,  `g.V.filter{it.age > 29}`

with anything larger than a  `2M` edges graph **results in the server to die!**
Additionally I do not find anything in the logs to explain what happened.

The console just returns a 

     [main] WARN  com.arangodb.http.HttpManager - The target server failed to respond
     org.apache.http.NoHttpResponseException: The target server failed to respond

**Comment by jsteemann** [comment]
The `GRAPH_VERTICES` function in 2.8 is implemented in JavaScript code and is executed using the V8 JavaScript engine. When it runs out of memory, it will call abort and terminate the arangod process ungracefully.
It may be useful to start the server with a special V8 option that allows it to use more memory for JavaScript execution: `--javascript.v8-options="max_old_space_size=8192"` (this means 8 GB max, probably even more is required).
The ungraceful termination by V8 also was the motivation for removing some of the JavaScript-based graph functions in the 3.0 release, and suggesting to use non-JavaScript variants in that version (please see https://docs.arangodb.com/cookbook/AQL/MigratingGraphFunctionsTo3.html).

**Comment by kuzeko** [comment]
Ok, thanks a lot! 

So the
`--javascript.v8-options="max_old_space_size=XXXX"`
mitigates the problem.

But leaves with a number of questions:

 0. Is this *ungraceful death* logged anywhere?

 1. Is it normal that any value larger than `2^16 -1 = 65535` causes:

       2017-01-03T19:54:40Z [849] INFO using V8 options '--max-old-space-size=65536'                                                           
       2017-01-03T19:54:40Z [849] ERROR JavaScript exception in file '/usr/share/arangodb/js/common/bootstrap/modules.js' at 534,13: ArangoError 3103: failed to invoke module\nFile: /usr/share/arangodb/js/server/modules/org/arangodb.js\nCause: TypeError: internal.db._modules.firstExample is not a function                                                                                                           
       2017-01-03T19:54:40Z [849] ERROR !      throw error;                                                                                    
       2017-01-03T19:54:40Z [849] ERROR !            ^                                                                                         
       2017-01-03T19:54:40Z [849] FATAL error during execution of JavaScript file 'server/initialize.js'

 2. **More importantly**: Those queries are translated by the *gremlin connector*, and bounded to the `2.8` version. This means that unless upgrading to 2.8 and until there is a new version of the connector, this is the best performance attainable now when issuing these queries?

Thanks a lot again for the quick reply!

**Comment by weinberger** [comment]
Q: 0. is this "ungraceful death" logged anywhere?
A. When V8 shuts down ungracefully, it will print a diagnostic message to standard out/standard err, but will not log it anywhere else (e.g. in a file). This is outside our control.

Q: Is it normal that any value larger than 2^16 -1 = 65535 causes...
A: the log output indicates that the option used was "--max-old-space-size=65536". I think it should be "--max_old_space_size=65536" instead (with underscores, not dashes). 
But apart from that, I don't get it to fail at startup even with much higher values. Additionally, the error message shown in the log output does not look related to increasing the max old space size, at least I don't see an obvious connection. Can you provide the full command line that you are using for starting arangod?
To finally answer your question, whatever value is provided for the startup parameter `--javascript.v8-options` is passed to V8 as is. arangod leaves it up to V8 to interpret and handle this value. The log output above indicates that V8 did not abort when processing the option value, so it's probably considered valid (even though the provided option name seems to be wrong).

Q: 2. More importantly: Those queries are translated by the gremlin connector, and bounded to the 2.8 version. This means that unless upgrading to 3.+ and until there is a new version of the connector, this is the best performance attainable now when issuing these queries?
A: That is the best what you can do at the moment if they are dependent on Gremlin. Blueprint is very Java-centric, and in addition, JS is involved. In many use cases the complete data, what is needed for the query, have to copy. If you want the best performance, you should consider using AQL instead. If you are afraid of the missing abstraction layer, you should think about other ways for that like data-centric microservcices via Foxx.

**Comment by kuzeko** [comment]
Thanks very much for the explanation, I think I'm getting to the bottom of it.

- RE Q0. I need to pass configurations options to V8 to obtain those logs. (Thinking that a query could *silently* kill the entire server is scary though)

- RE Q1. I'm passing the confs via a conf file:

        arangod  --daemon --pid-file /etc/arangodb/arangodb.pid -c /arangod.conf

    The relevant section  is the following

        [javascript]
        startup-directory = /usr/share/arangodb/js
        app-path = /var/lib/arangodb-apps
        v8-options = --max_old_space_size=65535
        #v8-options = --max-old-space-size=65535 also works
   
    and I can confirm that the above works both with dashes and underscores, up to 65535, those below are parsed and passed with quotes to V8 hence ignored

         v8-options = "--max_old_space_size=65535"
         v8-options = "max_old_space_size=65535"

    This only change in my conf value makes the  difference between the server to start and my query to run on one hand, and my query to miserably fail (when the argument is incorrectly parsed) or the server to fail starting when the value is above `2^16-1` on the other hand

- RE Q2. Here I'm slightly confused:   currently my understanding is that the gremlin console delivers the command to the arangodb-blueprints connector, which in turns translates it to the `HTTP` request containing the  `for i in GRAPH_VERTICES` lines and those are executed server side (and break the server). So this means that the problem is on the server side not handling the query and not on the gremlin (client) side.  Isn't the `HTTP` request forged by the arangodb-blueprints just containing an AQL query? Why should moving to AQL solve the problem if this blueprint implementation is already doing that for me?

**Comment by arcanefoam** [comment]
Closing this as the code base and versions supported have changed significantly. Please reopen if you continue to experience this issue.
